name: json-updater

on:
  pull_request:
    branches:
      - '*'
    tags:
      - '*'
  push:
    branches:
      - 'master'
  schedule:
    - cron:  '0 0-23 * * *' # every hour

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      
    - name: Configure git
      run: |
          cd /json-backups
          ls -las
          git config --global user.name "github-actions[bot]"
          git config --global user.email "stamepicmorg@users.noreply.github.com"

    - name: Update files
      run: |
          cd json-backups
          ls -las
          ./update.sh

    - name: Push updates
      run: |
          git add -A
          git commit -am "update"
          git push
