name: json-updater

on:
  pull_request:
    branches:
      - '*'
    tags:
      - '*'
  push:
    branches:
      - 'master'
  schedule:
    - cron:  '0 0-23 * * *' # every hour

jobs:
  update:

    runs-on: ubuntu-20.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Configure git
      run: |
          cd json-backups
          ls -las
          git config --global user.name "github-actions[bot]"
          git config --global user.email "stamepicmorg@users.noreply.github.com"

    - name: Update files
      run: |
          cd json-backups
          ls -las
          ./update.sh

    - name: Commit and push changes
      uses: devops-infra/action-commit-push@master
      with:
          github_token: ${{ secrets.GHT }}
          commit_message: Atlassian JSON updated
          commit_prefix: "[AUTO-COMMIT]"
