name: telegram-informer

on:
  workflow_dispatch:
  pull_request:
    branches:
      - '*'
    tags:
      - '*'
  push:
    branches:
      - 'master'

jobs:
  inform:

    runs-on: ubuntu-24.04

    steps:
     
      - name: Configure git
        run: |
          echo "Changes! Notify!"
          curl -s  --data-urlencode -X POST ${{ secrets.TLG_URL }} -d chat_id=${{ secrets.TLG_CHAT }} -d text="${{ secrets.TLG_TEXT }}" -d "parse_mode=HTML" >> /dev/null
