name: telegram-notifier

on:
  push:
    branches:
      - 'master'
    tags:
      - '*'

jobs:
  update:

    runs-on: ubuntu-20.04

    steps:
      - name: Notify 
        run: curl -s -X POST ${{ secrets.TLG_URL }} -d chat_id=${{ secrets.TLG_CHAT }} -d text="${{ secrets.TLG_TEXT }}"
